"""Builds a single, dependency-free Python script that can be piped into
`ssh <host> python3 -` to run perfmon's collectors on a remote machine
without installing anything there. The script is generated from the same
collector source files used locally (via inspect.getsource), so the remote
logic can never drift out of sync with the local logic.

The generated script loops forever, printing one JSON sample per line to
stdout (same shape as Sampler.sample()), spaced `interval` seconds apart.
"""
import inspect

from .collectors import psi as psi_mod
from .collectors import cpu as cpu_mod
from .collectors import memory as memory_mod
from .collectors import network as network_mod
from .collectors import disk as disk_mod
from .collectors import pci as pci_mod

# (module, bundle-local prefix); psi has no read/compute to rename.
_COLLECTOR_MODULES = [
    ("cpu", cpu_mod),
    ("memory", memory_mod),
    ("network", network_mod),
    ("disk", disk_mod),
    ("pci", pci_mod),
]

_MAIN_TEMPLATE = '''

def _collect_raw():
    return {
        "cpu": cpu_read(),
        "memory": memory_read(),
        "network": network_read(),
        "disk": disk_read(),
        "pci": pci_read(),
    }


def main():
    interval = __INTERVAL__
    prev = _collect_raw()
    prev_time = time.monotonic()
    while True:
        time.sleep(interval)
        curr = _collect_raw()
        now = time.monotonic()
        dt = now - prev_time
        sample = {
            "timestamp": time.time(),
            "dt": dt,
            "cpu": cpu_compute(prev["cpu"], curr["cpu"], dt),
            "memory": memory_compute(prev["memory"], curr["memory"], dt),
            "network": network_compute(prev["network"], curr["network"], dt),
            "disk": disk_compute(prev["disk"], curr["disk"], dt),
            "pci": pci_compute(prev["pci"], curr["pci"], dt),
        }
        try:
            sys.stdout.write(json.dumps(sample, default=str) + "\\n")
            sys.stdout.flush()
        except BrokenPipeError:
            return
        prev, prev_time = curr, now


if __name__ == "__main__":
    main()
'''


def _strip_relative_imports(src):
    return "\n".join(
        line for line in src.splitlines()
        if not line.strip().startswith("from .psi import")
    )


def _rename_module_functions(src, prefix):
    src = src.replace("def read(", f"def {prefix}_read(", 1)
    src = src.replace("def compute(", f"def {prefix}_compute(", 1)
    return src


def build_bundle(interval):
    """Return the full remote-collector script as a string."""
    parts = [
        "#!/usr/bin/env python3",
        "# Auto-generated by perfmon.bundler -- runs collectors standalone, no install required.",
        "import json, os, re, sys, time",
        "",
        inspect.getsource(psi_mod),
    ]
    for prefix, mod in _COLLECTOR_MODULES:
        src = _strip_relative_imports(inspect.getsource(mod))
        src = _rename_module_functions(src, prefix)
        parts.append(src)

    parts.append(_MAIN_TEMPLATE.replace("__INTERVAL__", repr(float(interval))))
    return "\n\n".join(parts)
